version: '2'
services:
    gateway-app:
        image: docker.io/deshetti/gateway
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - 'SPRING_PROFILES_ACTIVE=prod,swagger'
            - SPRING_CLOUD_CONSUL_HOST=consul
            - SPRING_CLOUD_CONSUL_PORT=8500
            - 'SPRING_DATA_MONGODB_URI=mongodb://gateway-mongodb:27017'
            - SPRING_DATA_MONGODB_DATABASE=gateway
            - 'SECURITY_OAUTH2_CLIENT_ACCESS_TOKEN_URI=http://keycloak:9080/auth/realms/jhipster/protocol/openid-connect/token'
            - 'SECURITY_OAUTH2_CLIENT_USER_AUTHORIZATION_URI=http://keycloak:9080/auth/realms/jhipster/protocol/openid-connect/auth'
            - SECURITY_OAUTH2_CLIENT_CLIENT_ID=web_app
            - SECURITY_OAUTH2_CLIENT_CLIENT_SECRET=web_app
            - SECURITY_OAUTH2_CLIENT_SCOPE=openid profile email
            - 'SECURITY_OAUTH2_RESOURCE_USER_INFO_URI=http://keycloak:9080/auth/realms/jhipster/protocol/openid-connect/userinfo'
            - JHIPSTER_SLEEP=10
            - 'SPRING_DATA_JEST_URI=http://gateway-elasticsearch:9200'
        ports:
            - '8080:8080'
    gateway-mongodb:
        image: 'mongo:4.0.2'
    gateway-elasticsearch:
        image: 'elasticsearch:5.6.5'
        command: '-Enetwork.host=0.0.0.0 -Ediscovery.type=single-node'
        environment:
            - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
    
    consul:
        extends:
            file: consul.yml
            service: consul
    consul-config-loader:
        extends:
            file: consul.yml
            service: consul-config-loader
    keycloak:
        extends:
            file: keycloak.yml
            service: keycloak
