#common configuration shared between all applications
configserver:
    name: Docker JHipster Registry
    status: Connected to Consul running in Docker

jhipster:
    security:
        authentication:
            jwt:
                base64-secret: MDIyYWZmM2Y4NDBjOWNmNDdlODMyN2I3NzJhMjhjMTM3MGI3NzkxMDdhMjdkYWVjYjViYmZkZTNhMDA1ZWUyMDAzNTUxMDMyOWM3ZDBkMDZlNDcxMGJiMGEzY2YzMzAwZWUwYQ==

